version: "3"

services:
  app:
    image: node:latest
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file: devcontainer.env
    user: node
    volumes:
      - ..:/home/node/project:cached
      - bashhistory:/commandhistory
      - node_modules:/node_modules
    ports:
      - "1234:1234"

volumes:
  bashhistory:
  node_modules: